### ISSUE TITLE
Symbol properties are ignored

### ISSUE THREAD

**Issue by natesilva** [mesqueeb/merge-anything#1]
Symbols can be used as property keys, but they are ignored.

```javascript
const merge = require('merge-anything');

const mySymbol = Symbol('mySymbol');

const x = { value: 42, [mySymbol]: 'hello' };

console.log(x);
// { value: 42, [Symbol(mySymbol)]: 'hello' }

const y = { other: 33 };
const z = merge(x, y);

console.log(z);
// { value: 42, other: 33 }
// expected: { value: 42, other: 33, [Symbol(mySymbol)]: 'hello' }
```

**Comment by mesqueeb** [comment]
@natesilva Thanks for this issue.
After looking into it it seems that Symbols are not iterated on via `Object.keys`, but instead I need to use `Object.getOwnPropertySymbols`.

I read other articles on Symbols and I'm confused why someone would ever need to use them.
Adding support for symbols would bloat the library, so I'm thinking how to best do this.

I guess I can just concat `Object.keys` with `Object.getOwnPropertySymbols` and iterate over everything.

But I wonder, why do you use symbols, and _should_ I iterate over them?

**Comment by natesilva** [comment]
We’re using the Sequelize ORM library. Queries use symbol operators. See [this documentation](http://docs.sequelizejs.com/manual/querying.html#operators) and the section following that, which talks about the security implications. I admit that don’t know how common this use case is, or if it will become more common in the future.

If you do implement it using `Object.getOwnPropertySymbols` and concatenating those keys with the string keys that you get from `Object.keys` would work. You should also consider filtering to those properties that are enumerable, since that is what `Object.keys` does; see [this documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Enumerability_and_ownership_of_properties).

**Comment by mesqueeb** [comment]
- if it's a symbol key, I'd also have to re-assign it as symbol key again.
- if it's an Nonenumerable prop, I'd have to re-assign it as Nonenumerable prop again.

Hmm. I'd welcome a PR if you're feeling like it.

**Comment by mesqueeb** [comment]
@natesilva I just finished complete support for
- (non- &) enumerable props
- (non- &) enumerable symbols
🎉

<sub>--<br>merge-anything was made with ♥ by Luca Ban.<br>If this library helped you in any way you can support me by buying me <a href="https://www.buymeacoffee.com/mesqueeb">a cup of coffee</a>. ☕️</sub>

**Comment by natesilva** [comment]
This is comprehensive and it works for us. Thank you!
