### ISSUE TITLE
Like Object.assign, but doesn't actually assign 

### ISSUE THREAD

**Issue by jakobrosenberg** [mesqueeb/merge-anything#12]
According to the README.md
> a simple merge function like Object.assign() but deep

I would expect the first object to be mutated if this is supposed to be a deep version of Object.assign.

Are there any options or plans to assign to the first object?

**Comment by mesqueeb** [comment]
Good catch! I wanna keep my tool that it does not mutate the first object, but only returns a new object without mutating.

So I'll have to clarify this difference in the docs !! 😮 

Thanks a lot for noticing!!

**Comment by jakobrosenberg** [comment]
Thanks I'll close this then.
