### ISSUE TITLE
ts-toolbelt dependency too loose

### ISSUE THREAD

**Issue by xenoterracide** [mesqueeb/merge-anything#13]
I'm getting this error using yarn2 with PnP

```
➤ YN0000: [@bb/graph-main]: ../../../../../.yarn/cache/ts-toolbelt-npm-8.4.0-f6995cd030-dbc3ad2626.zip/node_modules/ts-toolbelt/out/index.d.ts(983,46): error TS1110: Type expected.
```

```
> yarn why -R ts-toolbelt
└─ @bb/graph-main@workspace:ts/lib/graph/packages/main
   ├─ filter-anything@npm:2.1.6 (via npm:^2.1.6)
   │  └─ ts-toolbelt@npm:8.0.7 (via npm:8.0.7)
   └─ merge-anything@npm:3.0.6 (via npm:^3.0.6)
      └─ ts-toolbelt@npm:8.4.0 (via npm:^8.0.6)
```

the version I pulled in was 8.4.0, looking at the versions on ts-toolbelt that's `next`, not `latest`. I've worked around it by adding this to my `.yarnrc.yml`

```yml
packageExtensions:
  merge-anything@^3:
    dependencies:
      ts-toolbelt: '8.0'
```

P.S. it may also be worthwhile to loosen the dependency on filter-anything to be `8.0` instead of specifically `8.0.7`.

**Comment by mesqueeb** [comment]
@xenoterracide I'm not sure why ts-toolbelt is giving issues.

The version that's currently specified is ["ts-toolbelt": "^8.0.6"](https://github.com/mesqueeb/merge-anything/blob/11bb8259c90a858715af4f7c36bd95a02eac9c08/package.json#L49)

Are you sure this is an issue with my library and not ts-toolbelt? I'm interested in finding out what's wrong with the current setup, but I'm not sure how to debug this. : S

**Comment by xenoterracide** [comment]
my understanding is that the `^` is the problem, if you had `"ts-toolbelt": "8.0"` you would be fine. The `^` means any minor version later than `8.0.6` meaning that `8.0.7` and `8.4.0` are both valid. it seems obvious to me there is some backwards incompatibility (and maybe a bug) in ts-toolbelt 8.4. It's possible, that it's because the types resolved are at 2 different versions... I'm not certain on that. I can try to create a minimal reproduction later if needed, but it should be as easy as a yarn2 hello world with both of these libraries, and maybe only 1.

**Comment by fabiofdsantos** [comment]
I'm also having issues with `ts-toolbelt` v8.0.6. Might be related with TS version.

Example:
```
 ERROR  ERROR in node_modules/ts-toolbelt/out/index.d.ts(2148,9):
2148:9 A rest element must be last in a tuple type.
    2146 |     */
    2147 |     export type Concat<L extends List, L1 extends List> = [
  > 2148 |         ...L,
         |         ^
    2149 |         ...L1
    2150 |     ];
    2151 | }


 ERROR  ERROR in node_modules/ts-toolbelt/out/index.d.ts(6608,60):
6608:60 A rest element must be last in a tuple type.
    6606 |     ```
    6607 |     */
  > 6608 |     export type Pop<L extends List> = L extends (readonly [...infer LBody, any] | readonly [...infer LBody, any?]) ? LBody : L;
         |                                                            ^
    6609 | }
    6610 | declare module "List/Readonly" {
    6611 |     import { Depth } from "Object/_Internal";


 ERROR  ERROR in node_modules/ts-toolbelt/out/index.d.ts(6608,93):
6608:93 A rest element must be last in a tuple type.
    6606 |     ```
    6607 |     */
  > 6608 |     export type Pop<L extends List> = L extends (readonly [...infer LBody, any] | readonly [...infer LBody, any?]) ? LBody : L;
         |                                                                                             ^
    6609 | }
    6610 | declare module "List/Readonly" {
    6611 |     import { Depth } from "Object/_Internal";
```

**Comment by mesqueeb** [comment]
I reverted the library back to the old version `3.0.3` and re-published that as `3.0.7`.

If you need to use TypeScript 3.x please use that version.

I then published `4.0.0` which requires TypeScript 4.0 to work.

Please let me know if there's still any issues!

**Comment by xenoterracide** [comment]
I'm using typescript 4, so ts-toolbelt 8.4 (which is a beta release if my nomenclature about it being "next" and not "latest" is correct in the js world) would still be a problem.

**Comment by mesqueeb** [comment]
yes we use `ts-toolbelt` 8.0.7 and if there's a problem where `8.4.0` is not compatible with `8.0.7` then it's basically `ts-toolbelt`'s fault...

Can't you just use `ts-toolbelt@8.0.7`?

**Comment by xenoterracide** [comment]
I did, I specified it in `yarnrc` which is me overriding your dependencies, since I myself do not have a dependency on ts-toolbelt. you could just change your dependency to `8.0.x` instead of `^8.0.7` which can resolve to 8.4.

**Comment by xenoterracide** [comment]
yes, I set it to this, and I stopped getting compile errors

```yaml
  merge-anything@^3:
    dependencies:
      ts-toolbelt: 8.0
```

**Comment by mesqueeb** [comment]
Ok, to anyone coming here, if ts-toolbelt gives a problem because it's on `8.4` in one of your dependencies, you need to force it to `^8.0.0`

I'll close for now, because I don't believe there's any other solution.

**Comment by xenoterracide** [comment]
I created a repo that demonstrates this issue, https://github.com/xenoterracide/merge-anything-compilation-issues you can clone it and run `yarn && yarn build`

**Comment by xenoterracide** [comment]
cross referencing https://github.com/millsp/ts-toolbelt/issues/157

**Comment by xenoterracide** [comment]
from https://github.com/millsp/ts-toolbelt/issues/157

> I think that you need ts >= 4.1
> @mesqueeb's merge-anything is using the next version of ts-toolbelt. TypeScript 4.1 will be released in 5 days.

I think what you should do is release 4.0.1 with a dependency on `ts-toolbelt@8.0.x` and then once typescript 4.1 is out, make a 4.1.0 or 5.0 release for that (honestly, that's what `ts-toolbelt` should have done too)
