### ISSUE TITLE
🚨 Potential Improperly Controlled Modification of Object Prototype Attributes ('Prototype Pollution') (CWE-1321)

### ISSUE THREAD

**Issue by huntr-helper** [mesqueeb/merge-anything#20]
👋 Hello, @mesqueeb - a potential medium severity Improperly Controlled Modification of Object Prototype Attributes ('Prototype Pollution') (CWE-1321) vulnerability in your repository has been disclosed to us.

#### Next Steps

1️⃣  Visit **https://huntr.dev/bounties/1-other-mesqueeb/merge-anything** for more advisory information.

2️⃣  **[Sign-up](https://huntr.dev/)** to validate or speak to the researcher for more assistance.

3️⃣ Propose a patch or outsource it to our community - whoever fixes it gets paid.

---

#### Confused or need more help?

- Join us on our **[Discord](https://huntr.dev/discord)** and a member of our team will be happy to help! 🤗

- Speak to a member of our team: @JamieSlome

---

*This issue was automatically generated by [huntr.dev](https://huntr.dev) - a bug bounty board for securing open source code.*

**Comment by mesqueeb** [comment]
I don't see how this is relevant to my utility. It all depends on how you use it, whatever the dev merges with merge-anything. Not a real security issue imo. Let me know if otherwise.

**Comment by jayateertha043** [comment]
This issue is also very much related to https://github.com/mesqueeb/copy-anything/issues/10#issuecomment-835703439
Kindly read and validate if the vulnerability if you find this useful.

**Comment by mesqueeb** [comment]
@jayateertha043 can you make a PR that would fix the vulnerability ? I can consider releasing it in a major bump.
