### ISSUE TITLE
Arrays don't merge unless within an object.

### ISSUE THREAD

**Issue by coloredwax** [mesqueeb/merge-anything#22]
example: 

```js
import { mergeAndConcat } from "merge-anything";

console.log(mergeAndConcat([{ one: "two" }], [{ three: "four" }])) 
// output: [ { three: 'four' } ]
```

a simple workaround is this
```js
import { mergeAndConcat } from "merge-anything";

console.log(mergeAndConcat({ temp: [{ one: "two" }] }, { temp: [{ three: "four" }] }).temp) 
// output: [ { one: 'two' }, { three: 'four' } ]
```

I went to check if the **deepmerge** package supports this and it does it would be nice if **merge-anything** was to support this as well as I enjoy the suite of libs more

lol I realize this is the concat variant which is supposed to do this though it would be interesting to do like reverse depth

**Comment by coloredwax** [comment]
Hmm though the workaround wont merge root level arrays

**Comment by mesqueeb** [comment]
PRs welcome!
