### ISSUE TITLE
mergeAndCompare array more sharply, I can't distinguish between the new and old additions. 

### ISSUE THREAD

**Issue by productdevbook** [mesqueeb/merge-anything#34]
Test error: https://github.com/huntersofbook/huntersofbook/blob/29a836e9690b8c786ea89dddc55240447e016752/packages/schob/test/index.test.ts#L193

Library: https://github.com/huntersofbook/huntersofbook/tree/main/packages/schob

I created a new library using your libraries. But I have a problem with such a test.

Can you help by looking at the codes?

**Comment by mesqueeb** [comment]
@productdevbook I don't see any issues. can you send a screenshot of the error ?

**Comment by productdevbook** [comment]
![image](https://user-images.githubusercontent.com/38668796/201848045-96e8207f-77e9-4c86-b3bd-9de1f4384f35.png)

**Comment by mesqueeb** [comment]
@productdevbook is it ok for me to ask if you could add a PR that adds this failing test to my test files? It'll be easier for me to look into it this way.

**Comment by productdevbook** [comment]
Have you had time to look at the source code because I'm using your 3 libraries.

**Comment by productdevbook** [comment]
actually if i go into some detail, you add `undefined` without initial data in normal object, this works great.

![image](https://user-images.githubusercontent.com/38668796/201944929-5df39a9e-3417-4d5b-a944-332757a0bfe8.png)

But, object in array used, dont add `undefined` and the problem.

![image](https://user-images.githubusercontent.com/38668796/201945419-2fd90dcb-c0be-4b60-827c-c366bd420592.png)

**Comment by mesqueeb** [comment]
Yes it's just safer if I have the same tests in the source code of this repo. It's also easier for me to debug this way. Would be a great help. 

I think it's a type issue, I don't deeply merge the nested object types inside of arrays I believe. Will try to take a look this week.

**Comment by productdevbook** [comment]
Can I switch npm to pnpm if you have permission ? I will send a pr for it.

and array test pr.

**Comment by mesqueeb** [comment]
@productdevbook sadly I use `np` to make package releases and it doesn't support pnpm. 😭 I wish I could switch as well. But np is just too awesome to create releases. 

You could just add the test, I also use vitest, no need to do more testing yourself so you might be ok not installing the node modules 😁

**Comment by mesqueeb** [comment]
@productdevbook I was very confused with your tests. You were using that `convertTimestamps` example function that I provided, but seemed to want a completely different logic... 🤔 

I believe that perhaps you wanted to "merge all objects inside an array"?

If that's the case, this was already discussed in https://github.com/mesqueeb/merge-anything/issues/25

it's not a default behaviour of this library, so you have to write the compare fn yourself.

That said, I have written a simple version of it for you and added that as a new test on your branch. Can you check out the latest commit in your PR and let me know if this is what you wanted?

https://github.com/mesqueeb/merge-anything/pull/35

**Comment by mesqueeb** [comment]
@productdevbook thanks for your reply here
https://github.com/mesqueeb/merge-anything/pull/35#issuecomment-1317224079

Any use case for deeply merging arrays within objects can be achieved with the `mergeAndCompare` function. Based on the example I gave in the tests you can tweak this function to fit your situation. There is nothing you cannot achieve with this function, your only limit is your imagination.

I will close this issue now but feel free to open a new issue if you hit any reproducible bugs. 🙌🏻 

<sub>--<br />Merge Anything was made with 💜 by Luca Ban.<br />You cannot sponsor every project, but next time you do, think of <a href="https://github.com/sponsors/mesqueeb">this one</a> for its prolonged maintenance.</sub>

**Comment by productdevbook** [comment]
Thank you back,

Why is the content of undefined in the object not the same in the array? After all, there are objects in the array. Shouldn't it be subjected to the same function?

I think that it should be the same in the building sequence in the object.

**Comment by mesqueeb** [comment]
@productdevbook if you look closely at this line
https://github.com/mesqueeb/merge-anything/blob/production/test/mergeArrays.test.ts#L11
```ts
      .map((p, i) => (newVal[i] ? merge(p, newVal[i]) : p))
```

you will see that the compare function uses a nested `merge` call. You can tweak this logic to fit your needs by passing a nested `mergeAndCompare` function instead.
