### ISSUE TITLE
Browser support information

### ISSUE THREAD

**Issue by andi1984** [mesqueeb/merge-anything#4]
Could you share your intended browser support of this package in the README or in some kind of documentation?

**Comment by mesqueeb** [comment]
Howdy!
Thanks for your issue.
I'm not sure what you mean with "intended browser support" ?
I currently have two in-points in my `package.json`
```
"main": "dist/index.cjs.js",
"module": "dist/index.esm.js",
```

- "main" is the in-point for NodeJS apps that install it through NPM. It's built as a file with "commonJS" exports.
- "module" is the in-point for bundlers like: Rollup, Webpack, Parcel, etc... This is built as a file with "ES Module" exports.

Does this answer your question?

**Comment by andi1984** [comment]
Hi @mesqueeb,

thx for the fast response.

What I mean is about the intrinsic browser support for the ESM module which will be used by some bundler as you said and in the end lands in the browser on the client-side.

**Comment by mesqueeb** [comment]
@andi1984 I don't know with "intrinsic browser support". 😅 

You can use BABEL or TypeScript with your bundler to polyfill for any JS that's not yet supported right?
I'm pretty sure you don't need to go manually check the code of every single package in your dependencies 😆 

Sorry I don't know the exact question! 😢

**Comment by mesqueeb** [comment]
I'm going to close this issue, because I'm not sure what you mean.
Feel free to re-open with extra clarification!
