### ISSUE TITLE
package.json still contains exports for cjs

### ISSUE THREAD

**Issue by TimKolberger** [mesqueeb/merge-anything#42]
The `exports` field in version 6.0.0 still has a reference to missing cjs files:

https://github.com/mesqueeb/merge-anything/blob/202984e942806fdca62a81b526f8fc35aa29a8ef/package.json#L9-L12

I think those lines just need to be removed.

**Comment by TimKolberger** [comment]
Fixed in 6.0.2

**Comment by mesqueeb** [comment]
@TimKolberger thanks for this report! I forgot to close out the issue. 😭
