### ISSUE TITLE
Broken module resolution

### ISSUE THREAD

**Issue by woodcockjosh** [mesqueeb/merge-anything#43]
I get this error when trying to import your project. 

```
Cannot find module 'merge-anything' or its corresponding type declarations.
  There are types at '{project path}/node_modules/merge-anything/dist/index.d.ts', but this result could not be resolved under your current 'moduleResolution' setting. Consider updating to 'node16', 'nodenext', or 'bundler'.
  ```

Whatever settings this package is using, is not the same as all other typescript npm packages

The only way to get this package to work is to use `const MergeAnything = require("merge-anything")` es6 style imports like `import { merge } from "merge-anything"` do not work. For reference here is my `tsconfig.json`

```json
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "noImplicitAny": false,
    "removeComments": true,
    "noLib": false,
    "allowSyntheticDefaultImports": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es2017",
    "sourceMap": true,
    "outDir": "./lib",
    "baseUrl": "./src",
    "types": ["node", "i18n", "jest"],
    "resolveJsonModule": true
  },
  "include": [
    "src/**/*"
  ],
  "exclude": [
    "node_modules", "**/*.spec.ts"
  ],
  "il18n": [
    "eng-US"
  ]
}
```

**Comment by woodcockjosh** [comment]
I have created a package `@cryptexlabs/merge-anything` that uses `commonjs` instead of `nodenext ` for module resolution for anyone that comes across the same issue.

**Comment by mesqueeb** [comment]
This package is esm only. Does not support commonjs. 

Please consider upgrading to esm.
