### ISSUE TITLE
Merge anything compile error fails in typescript

### ISSUE THREAD

**Issue by SpudNyk** [mesqueeb/merge-anything#7]
The line in merge.d.ts fails for me when importing
```
declare type PlainObject = {
    [key: string | symbol]: any;
};
```

I notice that in merge.ts the same problem line is: 
```
// @ts-ignore
type PlainObject = { [key: string | symbol]: any }
```
Is it possible to fix this?

**Comment by mesqueeb** [comment]
@SpudNyk thanks for reporting. I have some ideas of how I can solve this. I will push update in a few hours. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mesqueeb** [comment]
@SpudNyk Internally I still use 
```ts
// @ts-ignore
type PlainObject = { [key: string | symbol]: any }
```
but the external API now only uses the typescript `object` type.

Can you try install the latest version and let me know if this solves your problem?
Cheers!

<sub>--<br>Merge Anything was made with ♥ by Luca Ban.<br>If you use this library in your projects, you can support the maintenance of this library by a small <a href="https://github.com/sponsors/mesqueeb">contribution via Github 💜</a>.<br>You can also reach out <a href="https://twitter.com/mesqueeb">on twitter</a> if you want a one-on-one coding review/lesson. 🦜</sub>

**Comment by SpudNyk** [comment]
@mesqueeb can confirm that it's fine now - thanks for the fast update.
