### ISSUE TITLE
merge fails on imported objects

### ISSUE THREAD

**Issue by dsl101** [mesqueeb/merge-anything#9]
In relation to [this](https://github.com/mesqueeb/vuex-easy-firestore/issues/313), here's a relatively simple demonstration of the problem:

```
// getters.js
export const meaning = () => 42


// index.js
import * as getters from './getters'
import { merge } from 'merge-anything'

const otherThing = {
  something () { return 'anything' }
}

console.log('getters:', getters)
console.log('otherThing:', otherThing)
console.log('merge(getters, otherThing):', merge(getters, otherThing))
console.log('merge(otherThing, getters):', merge(otherThing, getters))
```

The result of the merge is just the second argument, not a merge:

![image](https://user-images.githubusercontent.com/900542/78818641-e164f280-79cc-11ea-968c-34663d3900b9.png)

**Comment by mesqueeb** [comment]
@dsl101 Thanks for the issue!
Again, this is not really anything I can help.
BTW, did know that you can transform a bunch of values you import into a regular JS object?

```js
import * as importedStuff from './somewhere'

const regularObject = { ...importedStuff }
```

I think this might help you out ;)

<sub>--<br>Merge Anything was made with ♥ by Luca Ban.<br>If you use this library in your projects, you can support the maintenance of this library by a small <a href="https://github.com/sponsors/mesqueeb">contribution via Github 💜</a>.<br>You can also reach out <a href="https://twitter.com/mesqueeb">on twitter</a> if you want a one-on-one coding review/lesson. 🦜</sub>
